# -*- coding: utf-8 -*-
"""Fish_price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2zPvaqeJ5utQjj2SQsYUNGSNEr_7RTN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Fish (1).csv')

df.head()

df.describe()

sns.heatmap(df.corr())

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Species']= label_encoder.fit_transform(df['Species'])

df.head()

X = df.drop(['Price'],axis=1)
y = df['Price']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor()

reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)

reg.score(X_test,y_test)

from sklearn.externals import joblib
joblib.dump(reg, 'model_fish2.pkl')

model = joblib.load(open("model_fish2.pkl", 'rb'))

import pickle
pickle.dump(reg, open('model_fish1.pkl', 'wb'))

model = pickle.load(open("model_fish1.pkl", 'rb'))

print(model.predict([[0,23,25,30,12,4]]))

